name: flake8

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Setup packages
        shell: bash
        run: |
          python -m pip install flake8-nb
      - name: Lint notebooks
        shell: bash
        run: |
          flake8-nb