# This is a basic workflow to help you get started with Actions

name: CI # name that will show on GH actions page

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "testCI"
  testCI:
    name: Testing on OS ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: devtools/env.yaml
          activate-environment: dl-review

      - name: Check conda environment
        shell: bash -l {0}
        run: conda list


